# Generated by Django 4.2.23 on 2025-08-22 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('topic', models.CharField(choices=[('order', 'Вопрос по заказу'), ('product', 'Вопрос по товару'), ('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('other', 'Другое')], default='order', max_length=20, verbose_name='Тема обращения')),
                ('custom_topic', models.CharField(blank=True, max_length=255, verbose_name='Тема не из списка')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='Авторизованный пользователь (если есть)', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'feedback_messages',
            },
        ),
    ]
