# Generated by Django 5.2.4 on 2025-08-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='phone',
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='custom_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема не из списка'),
        ),
    ]
