# Generated by Django 5.2.4 on 2025-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedbackmessage_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='status',
            field=models.CharField(choices=[('order', 'Вопрос по заказу'), ('product', 'Вопрос по товару'), ('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('other', 'Другое')], default='new', max_length=20, verbose_name='Статус обращения'),
        ),
    ]
