# Generated by Django 5.2.4 on 2025-08-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedbackmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('answered', 'Отвечено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус обращения'),
        ),
    ]
