# Generated by Django 4.2.23 on 2025-08-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_author_alter_review_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
