# Generated by Django 5.2.4 on 2025-08-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
