# Generated by Django 4.2.23 on 2025-08-20 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_quantity_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(max_length=100, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 12, 54, 51, 82165), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Скидка в %'),
        ),
    ]
