# Generated by Django 4.2.23 on 2025-08-20 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_key_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 1, 19, 578906), verbose_name='Дата добавления'),
        ),
    ]
