# Generated by Django 4.2.23 on 2025-08-20 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 16, 50, 20, 130197), verbose_name='Дата добавления'),
        ),
    ]
