# Generated by Django 4.2.23 on 2025-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='bi-box', null=True, verbose_name='Иконка для категории'),
        ),
    ]
