# Generated by Django 5.2.4 on 2025-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='bi-box', max_length=100, null=True, verbose_name='Иконка для категории'),
        ),
    ]
