# Generated by Django 5.2.4 on 2025-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзывы о заказах', 'verbose_name_plural': 'Отзывы о заказах'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзывы о товарах', 'verbose_name_plural': 'Отзывы о товарах'},
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
