# Generated by Django 4.2.23 on 2025-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_orderreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='status',
            field=models.CharField(choices=[('moderating', 'На модерации'), ('published', 'Опубликован'), ('cancelled', 'Отклонен')], default='На модерации', max_length=20, verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('moderating', 'На модерации'), ('published', 'Опубликован'), ('cancelled', 'Отклонен')], default='На модерации', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
