# Generated by Django 4.2.23 on 2025-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_orderreview_status_productreview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreview',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='is_published',
        ),
        migrations.AddField(
            model_name='orderreview',
            name='reason_for_cancel',
            field=models.CharField(choices=[('-', '-'), ('spam', 'Спам или реклама'), ('false_info', 'Ложная информация о продукте'), ('misleading', 'Вводящие в заблуждение сведения'), ('no_details', 'Отсутствие конкретики ("хороший/плохой")'), ('advertising', 'Реклама конкурентов'), ('off_topic', 'Не относится к продукту'), ('duplicate', 'Дублирующий отзыв'), ('offensive', 'Оскорбительные высказывания'), ('personal_data', 'Раскрытие персональных данных')], default='-', max_length=50, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reason_for_cancel',
            field=models.CharField(choices=[('-', '-'), ('spam', 'Спам или реклама'), ('false_info', 'Ложная информация о продукте'), ('misleading', 'Вводящие в заблуждение сведения'), ('no_details', 'Отсутствие конкретики ("хороший/плохой")'), ('advertising', 'Реклама конкурентов'), ('off_topic', 'Не относится к продукту'), ('duplicate', 'Дублирующий отзыв'), ('offensive', 'Оскорбительные высказывания'), ('personal_data', 'Раскрытие персональных данных')], default='-', max_length=50, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('moderating', 'На модерации'), ('published', 'Опубликован'), ('cancelled', 'Отклонен')], default='moderating', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
