# Generated by Django 4.2.23 on 2025-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_orderreview_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='reason_for_cancel',
            field=models.CharField(choices=[('-', '-'), ('spam', 'Спам или реклама'), ('false_info', 'Ложная информация о продукте'), ('misleading', 'Вводящие в заблуждение сведения'), ('no_details', 'Отсутствие конкретики ("хороший/плохой")'), ('advertising', 'Реклама конкурентов'), ('off_topic', 'Не относится к продукту'), ('duplicate', 'Дублирующий отзыв'), ('offensive', 'Оскорбительные высказывания'), ('personal_data', 'Раскрытие персональных данных'), ('delayed', 'Отзыв опубликуется спустя 14 дней после первой покупки')], default='-', max_length=50, verbose_name='Причина отказа'),
        ),
    ]
