# Generated by Django 5.2.4 on 2025-08-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_productreview_reason_for_cancel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о заказе', 'verbose_name_plural': 'Отзывы о заказах'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о товаре', 'verbose_name_plural': 'Отзывы о товарах'},
        ),
    ]
